# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x
    - name: Restore dependencies
      run: dotnet restore ./LightManager.PanelUi/LightManager.PanelUi.csproj
    - name: Build
      run: dotnet build ./LightManager.PanelUi/LightManager.PanelUi.csproj --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  docker-arm64:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # Uncomment and configure the following if you want to push to DockerHub
      # - name: Login to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image for arm64/v8
        run: |
          docker buildx build \
            --platform linux/arm64/v8 \
            -t t-tibor94/light-manager:arm64-latest \
            --load \
            -f ./LightManager.PanelUiDockerfile \
            .
            

